version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  clientapp:
    build:
      context: .
      dockerfile: WebNewsAggregator.ClientApp/Dockerfile
    ports:
      - "5111:80"
    depends_on:
      - db

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080