version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080